const dummyPosts = [
    {
        id: 1,
        desc: 'The quick brown fox jumps over the lazy dog',
        username: 'nilaacode1',
        social_username: 'nilaacode1',
        twitter: true,
        instagram: false,
        github: false,
        created_at: '2024-03-19',
        upvotes: 69,
    },
    {
        id: 2,
        desc: 'A journey of a thousand miles begins with a single step',
        username: 'nilaacode2',
        social_username: 'nilaacode2',
        twitter: false,
        instagram: true,
        github: false,
        created_at: '2024-03-20',
        upvotes: 45,
    },
    {
        id: 3,
        desc: 'To be or not to be, that is the question',
        username: 'nilaacode3',
        social_username: 'nilaacode3',
        twitter: false,
        instagram: false,
        github: true,
        created_at: '2024-03-21',
        upvotes: 88,
    },
    {
        id: 4,
        desc: 'All that glitters is not gold',
        username: 'nilaacode4',
        social_username: 'nilaacode4',
        twitter: true,
        instagram: true,
        github: false,
        created_at: '2024-03-22',
        upvotes: 32,
    },
    {
        id: 5,
        desc: 'The early bird catches the worm',
        username: 'nilaacode5',
        social_username: 'nilaacode5',
        twitter: false,
        instagram: false,
        github: true,
        created_at: '2024-03-23',
        upvotes: 27,
    },
    {
        id: 6,
        desc: 'A picture is worth a thousand words',
        username: 'nilaacode6',
        social_username: 'nilaacode6',
        twitter: true,
        instagram: false,
        github: false,
        created_at: '2024-03-24',
        upvotes: 54,
    },
    {
        id: 7,
        desc: 'Actions speak louder than words',
        username: 'nilaacode7',
        social_username: 'nilaacode7',
        twitter: false,
        instagram: true,
        github: false,
        created_at: '2024-03-25',
        upvotes: 61,
    },
    {
        id: 8,
        desc: 'A watched pot never boils',
        username: 'nilaacode8',
        social_username: 'nilaacode8',
        twitter: false,
        instagram: false,
        github: true,
        created_at: '2024-03-26',
        upvotes: 19,
    },
    {
        id: 9,
        desc: 'Better late than never',
        username: 'nilaacode9',
        social_username: 'nilaacode9',
        twitter: true,
        instagram: false,
        github: false,
        created_at: '2024-03-27',
        upvotes: 73,
    },
    {
        id: 10,
        desc: 'Birds of a feather flock together',
        username: 'nilaacode10',
        social_username: 'nilaacode10',
        twitter: false,
        instagram: true,
        github: false,
        created_at: '2024-03-28',
        upvotes: 36,
    },
    {
        id: 11,
        desc: 'Do not count your chickens before they hatch',
        username: 'nilaacode11',
        social_username: 'nilaacode11',
        twitter: false,
        instagram: false,
        github: true,
        created_at: '2024-03-29',
        upvotes: 44,
    },
    {
        id: 12,
        desc: 'Do not put all your eggs in one basket',
        username: 'nilaacode12',
        social_username: 'nilaacode12',
        twitter: true,
        instagram: false,
        github: false,
        created_at: '2024-03-30',
        upvotes: 56,
    },
    {
        id: 13,
        desc: 'Do unto others as you would have them do unto you',
        username: 'nilaacode13',
        social_username: 'nilaacode13',
        twitter: false,
        instagram: true,
        github: false,
        created_at: '2024-03-31',
        upvotes: 29,
    },
    {
        id: 14,
        desc: 'Honesty is the best policy',
        username: 'nilaacode14',
        social_username: 'nilaacode14',
        twitter: false,
        instagram: false,
        github: true,
        created_at: '2024-04-01',
        upvotes: 82,
    },
    {
        id: 15,
        desc: 'Practice makes perfect',
        username: 'nilaacode15',
        social_username: 'nilaacode15',
        twitter: true,
        instagram: false,
        github: false,
        created_at: '2024-04-02',
        upvotes: 91,
    }
];
export default dummyPosts;